package org.dei.perla.lang;

import org.dei.perla.core.fpc.Attribute;

import java.util.List;

/**
 * Contains a single record generated by a PerLa query
 *
 * @author Guido Rota 03/07/15.
 */
public final class Record {

    private final List<Attribute> fields;
    private final Object[] values;

    public Record(List<Attribute> fields, Object[] values) {
        this.fields = fields;
        this.values = values;
    }

    public List<Attribute> getFields() {
        return fields;
    }

    public Object[] getValues() {
        return values;
    }

    @Override
    public String toString() {
        StringBuilder bld = new StringBuilder();
        bld.append("[");
        for (int i = 0; i < fields.size(); i++) {
            Attribute a = fields.get(i);
            Object v = values[i];
            bld.append(a).append(": ").append(v).append(", ");
        }
        bld.append("]");
        return bld.toString();
    }

}
